//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gameStore.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLines
    {
        public int OrderLineID { get; set; }
        public int Quantity { get; set; }
        public int Game_GameID { get; set; }
        public int Order_OrderID { get; set; }
    
        public virtual Games Games { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
